[package]
name = "soma-rendezvous"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
soma-core = { workspace = true }
soma-net = { workspace = true }
soma-metrics = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
futures = { workspace = true }
prometheus-client = { workspace = true }
axum = { workspace = true }
prometheus-client-derive-encode = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
