version: 2
updates:
  - package-ecosystem: cargo
    directory: "/backend"
    schedule:
      interval: weekly
      time: "08:00"
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "08:00"
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/desktop"
    schedule:
      interval: weekly
      time: "08:00"
    open-pull-requests-limit: 3