[workspace]
members = [
    "crates/core",
    "crates/storage",
    "crates/net",
    "crates/api",
    "crates/agent",
    "crates/common",
    "crates/membership",
    "crates/proto-build",
    "crates/metrics",
    "crates/relay",
    "crates/rendezvous",
    "crates/bff",
    "crates/peer",
    "crates/socket",
    "bins/daemon",
    "bins/botd",
    "bins/agentd",
    "bins/relayd",
    "bins/rendezvousd",
    "bins/bffd",
    "bins/serverd",
]

resolver = "3"

[workspace.dependencies]
soma-core = { path = "crates/core" }
soma-storage = { path = "crates/storage" }
soma-net = { path = "crates/net" }
soma-api = { path = "crates/api" }
soma-agent = { path = "crates/agent" }
soma-common = { path = "crates/common" }
soma-membership = { path = "crates/membership" }
soma-rendezvous = { path = "crates/rendezvous" }
soma-relay = { path = "crates/relay" }
soma-bff = { path = "crates/bff" }
soma-peer = { path = "crates/peer" }
soma-socket = { path = "crates/socket" }
soma-metrics = { path = "crates/metrics" }
soma-proto-build = { path = "crates/proto-build" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
derive_builder = "0.20"

prost = "0.14"
prost-types = "0.14"
tokio-stream = "0.1"
async-trait = "0.1"
tonic = { version = "0.14", features = ["transport"] }
tonic-prost = "0.14"
tonic-build = { version = "0.14" }
tonic-prost-build = { version = "0.14" }
prost-build = { version = "0.14" }
walkdir = { version = "2.5" }

rand = "0.9"
clap = { version = "4", features = ["derive", "env"] }

anyhow = "1"
thiserror = "2"

axum = { version = "0.8" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }

tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing = { version = "0", features = ["attributes", "async-await", "std"] }

mimalloc = "0"
futures = "0.3"
prometheus-client = "0.22"
prometheus-client-derive-encode = "0.4"
tempfile = "3"
base64 = "0.22"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "macros", "any", "postgres", "sqlite", "migrate", "time", "chrono", "json"] }
sqlx-utils = "1.1.3"
ciborium = "0.2"

[workspace.dependencies.libp2p]
version = "0.56"
features = [
    "tcp", "quic", "websocket", "relay", "rendezvous",
    "autonat", "noise", "tls", "cbor", "mdns", "kad",
    "tokio", "dns", "gossipsub", "macros", "upnp",
    "yamux", "ping", "ecdsa", "identify", "request-response"
]

[profile.prod]
inherits = "release"
lto = true
opt-level = "z"
codegen-units = 1
incremental = false
strip = true

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false
authors = [
    "Stephane Segning <selastlambou@gmail.com>"
]
