[package]
name = "soma-daemon"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "soma_daemon"
path = "src/lib.rs"

[dependencies]
soma-core = { workspace = true, features = ["db"] }
soma-storage = { workspace = true }
soma-net = { workspace = true }
soma-api = { workspace = true }
soma-common = { workspace = true }
soma-vdfs = { workspace = true }
soma-peer = { workspace = true }
soma-proto-build = { workspace = true }
soma-membership = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
prost-types = { workspace = true }
prost = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
futures = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "migrate", "runtime-tokio-rustls"] }
sha2 = { workspace = true }
