import type { MentionProvider } from "@soma/editor";
import { useMemo } from "react";
import * as documentsService from "../../../services/documents-service";
import * as spacesService from "../../../services/spaces-service";
import { UNTITLED_PAGE_TITLE } from "../page-title";

/**
 * Shortens a peer ID to a readable suffix used as a fallback label when a
 * bot has no operator-assigned alias.  Mirrors the `bot-<peerSuffix>`
 * placeholder generated by `toBot()` in `space-settings/use-space-bots.ts`
 * (last 6 chars, lowercased) so the same bot renders the same fallback
 * label across the mention picker and the Bots settings tab.
 */
function peerSuffix(peerId: string): string {
	return peerId.slice(-6).toLowerCase() || "bot";
}

export function usePageMentionProviders(spaceId: string): MentionProvider[] {
	return useMemo<MentionProvider[]>(() => {
		const peerMention: MentionProvider = {
			name: "peerMention",
			char: "@",
			placeholder: "Mention a peer",
			section: "members",
			items: async (query) => {
				const members = await spacesService.listSpaceMembers(spaceId);
				const trimmed = query.trim().toLowerCase();
				return members
					.filter((member) => (trimmed ? member.peerId.toLowerCase().includes(trimmed) : true))
					.map((member) => ({
						id: member.peerId,
						label: member.peerId,
						detail: member.role,
						href: `/spaces/${spaceId}/members?peerId=${member.peerId}`,
					}));
			},
		};

		const spaceMention: MentionProvider = {
			name: "spaceMention",
			char: "%",
			placeholder: "Mention a space",
			section: "spaces",
			items: async (query) => {
				const result = await spacesService.listSpaces({ query });
				return result.spaces.map((space) => ({
					id: space.spaceId,
					label: space.displayName || space.spaceId,
					detail: space.spaceId,
					href: `/spaces/${space.spaceId}`,
				}));
			},
		};

		const pageMention: MentionProvider = {
			name: "pageMention",
			char: "#",
			placeholder: "Mention a page",
			section: "documents",
			items: async (query) => {
				const pages = await documentsService.listPages({ spaceId });
				const trimmed = query.trim().toLowerCase();
				return pages
					.filter((page) => {
						if (!trimmed) return true;
						const title = (page.title ?? "").toLowerCase();
						return title.includes(trimmed) || page.pageId.toLowerCase().includes(trimmed);
					})
					.map((page) => ({
						id: page.pageId,
						label: page.title || UNTITLED_PAGE_TITLE,
						detail: page.pageId,
						href: `/spaces/${spaceId}/pages/${page.pageId}`,
					}));
			},
		};

		/**
		 * Bot mention — trigger char `!`.
		 *
		 * Rationale for a separate char rather than an `@bot:` prefix:
		 * `@` is already claimed by the members provider and tiptap
		 * Suggestion matches on a single trigger character.  Routing on a
		 * prefix would require either pre-filter logic in the members
		 * provider or a custom `findSuggestion` override — both add
		 * fragile state.  A dedicated `!` char keeps each provider
		 * fully independent, matches the codebase's one-provider-per-char
		 * pattern, and aligns with the UI copy (`!bot-alias` in the editor,
		 * `@bot:alias` in chat where a richer composer can pre-parse the
		 * prefix before dispatching to the picker).
		 */
		const botMention: MentionProvider = {
			name: "botMention",
			char: "!",
			placeholder: "Mention a bot",
			section: "bots",
			items: async (query) => {
				const bots = await spacesService.listSpaceBots(spaceId);
				const trimmed = query.trim().toLowerCase();
				return bots
					.filter((bot) => {
						if (!trimmed) return true;
						const alias = bot.alias?.trim().toLowerCase() ?? "";
						const suffix = peerSuffix(bot.peerId);
						return alias.includes(trimmed) || suffix.includes(trimmed);
					})
					.map((bot) => {
						const trimmedAlias = bot.alias?.trim();
						const label = trimmedAlias || `bot-${peerSuffix(bot.peerId)}`;
						return {
							id: bot.peerId,
							label,
							detail: peerSuffix(bot.peerId),
							href: `/spaces/${spaceId}/settings/bots?peerId=${bot.peerId}`,
						};
					});
			},
		};

		return [peerMention, spaceMention, pageMention, botMention];
	}, [spaceId]);
}
