// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	dbStorageGet: (key: string) => typedError<string | null, DesktopError>(__TAURI_INVOKE("db_storage_get", { key })),
	dbStorageSet: (key: string, value: string) => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_set", { key, value })),
	dbStorageRemove: (key: string) => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_remove", { key })),
	dbStorageClear: () => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_clear")),
	dbStorageKeys: () => typedError<string[], DesktopError>(__TAURI_INVOKE("db_storage_keys")),
	settingsGet: (args: SettingsGetArgs) => typedError<string | null, DesktopError>(__TAURI_INVOKE("settings_get", { args })),
	settingsSet: (args: SettingsSetArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("settings_set", { args })),
	settingsGetAll: () => typedError<string, DesktopError>(__TAURI_INVOKE("settings_get_all")),
	windowControl: (args: WindowControlArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("window_control", { args })),
	windowMinimize: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_minimize")),
	windowToggleMaximize: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_toggle_maximize")),
	windowClose: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_close")),
	daemonStatus: () => typedError<DaemonStatus, DesktopError>(__TAURI_INVOKE("daemon_status")),
	daemonReady: () => typedError<boolean, DesktopError>(__TAURI_INVOKE("daemon_ready")),
	daemonControl: (args: ControlArgs) => typedError<ControlResult, DesktopError>(__TAURI_INVOKE("daemon_control", { args })),
	spacesList: (args: {
	q: string | null,
	limit?: number,
	offset?: number,
} | null) => typedError<ListSpacesResult, DesktopError>(__TAURI_INVOKE("spaces_list", { args })),
	spacesCreate: (args: {
	spaceId?: string | null,
	displayName?: string | null,
} | null) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_create", { args })),
	spacesGet: (spaceId: string) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_get", { spaceId })),
	spacesUpdate: (args: UpdateSpaceArgs) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_update", { args })),
	spacesDelete: (spaceId: string) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_delete", { spaceId })),
	spacesListMembers: (spaceId: string) => typedError<StoredSpaceMember[], DesktopError>(__TAURI_INVOKE("spaces_list_members", { spaceId })),
	spacesListMyMemberships: () => typedError<StoredSpaceMember[], DesktopError>(__TAURI_INVOKE("spaces_list_my_memberships")),
	spacesListBots: (spaceId: string) => typedError<StoredSpaceBot[], DesktopError>(__TAURI_INVOKE("spaces_list_bots", { spaceId })),
	spacesJoin: (args: JoinSpaceArgs) => typedError<JoinSpaceResult, DesktopError>(__TAURI_INVOKE("spaces_join", { args })),
	spacesDecideJoin: (args: DecideJoinArgs) => typedError<DecideJoinResult, DesktopError>(__TAURI_INVOKE("spaces_decide_join", { args })),
	spacesListJoinRequests: () => typedError<StoredJoinRequest[], DesktopError>(__TAURI_INVOKE("spaces_list_join_requests")),
	spacesRevokeMember: (args: RevokeMemberArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_revoke_member", { args })),
	spacesIssueIssuerCapability: (args: IssueIssuerCapabilityArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_issue_issuer_capability", { args })),
	documentsUpsert: (args: UpsertDocumentArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("documents_upsert", { args })),
	documentsGet: (spaceId: string, documentId: string) => typedError<{
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: boolean,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_get", { spaceId, documentId })),
	documentsEnsurePage: (args: EnsurePageArgs) => typedError<StoredPage, DesktopError>(__TAURI_INVOKE("documents_ensure_page", { args })),
	documentsListPages: (spaceId: string) => typedError<StoredPage[], DesktopError>(__TAURI_INVOKE("documents_list_pages", { spaceId })),
	documentsUpdatePageTitle: (args: UpdatePageTitleArgs) => typedError<{
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_update_page_title", { args })),
	documentsSetPageParents: (args: SetPageParentsArgs) => typedError<{
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_set_page_parents", { args })),
	blobsUpload: (args: UploadBlobArgs) => typedError<UploadBlobResult, DesktopError>(__TAURI_INVOKE("blobs_upload", { args })),
	blobsRead: (spaceId: string, cid: string) => typedError<number[] | null, DesktopError>(__TAURI_INVOKE("blobs_read", { spaceId, cid })),
	blobsStageUpload: (args: StageUploadArgs) => typedError<StagedUpload, DesktopError>(__TAURI_INVOKE("blobs_stage_upload", { args })),
	agentChatStream: (args: ChatStreamArgs_Deserialize) => typedError<ChatResponse, DesktopError>(__TAURI_INVOKE("agent_chat_stream", { args })),
	agentListModels: (spaceId: string | null) => typedError<AgentModel_Serialize[], DesktopError>(__TAURI_INVOKE("agent_list_models", { spaceId })),
	agentRerank: (args: RerankParams) => typedError<RerankResult[], DesktopError>(__TAURI_INVOKE("agent_rerank", { args })),
	agentResolveDrift: (args: ResolveDriftParams) => typedError<ResolveDriftResult, DesktopError>(__TAURI_INVOKE("agent_resolve_drift", { args })),
	agentEnqueueBackgroundTask: (args: EnqueueBackgroundTaskParams) => typedError<BackgroundTask, DesktopError>(__TAURI_INVOKE("agent_enqueue_background_task", { args })),
	agentListBackgroundTasks: (args: {
	spaceId: string | null,
	limit: number | null,
} | null) => typedError<BackgroundTask[], DesktopError>(__TAURI_INVOKE("agent_list_background_tasks", { args })),
	search: (query: string | null) => typedError<SearchResult[], DesktopError>(__TAURI_INVOKE("search", { query })),
};

/* Types */
export type AgentModel = AgentModel_Serialize | AgentModel_Deserialize;

export type AgentModel_Deserialize = {
	name: string,
	kind: ModelKind,
	path: string,
	loaded: boolean,
	sizeBytes: number | null,
};

export type AgentModel_Serialize = {
	name: string,
	kind: ModelKind,
	path: string,
	loaded: boolean,
	sizeBytes?: number | null,
};

export type AgentProvider = 
/**  Any HTTP endpoint speaking the OpenAI REST shape (Ollama, vLLM, OpenAI proper, etc.). */
"open-ai-compatible";

export type AgentRuntimeEvent = AgentRuntimeEvent_Serialize | AgentRuntimeEvent_Deserialize;

export type AgentRuntimeEvent_Deserialize = ({ kind: "ready"; atMs: number; provider: AgentProvider; baseUrl: string }) & { error?: never; models?: never } | ({ kind: "status"; atMs: number; provider: AgentProvider; baseUrl: string; models: AgentModel_Deserialize[] }) & { error?: never } | ({ kind: "error"; atMs: number; provider: AgentProvider; baseUrl: string; error: string }) & { models?: never };

export type AgentRuntimeEvent_Serialize = ({ kind: "ready"; atMs: number; provider: AgentProvider; baseUrl: string }) & { error?: never; models?: never } | ({ kind: "status"; atMs: number; provider: AgentProvider; baseUrl: string; models: AgentModel_Serialize[] }) & { error?: never } | ({ kind: "error"; atMs: number; provider: AgentProvider; baseUrl: string; error: string }) & { models?: never };

export type AppInfo = {
	name: string,
	version: string,
	tauri: string,
};

export type BackgroundTask = {
	taskId: string,
	kind: BackgroundTaskKind,
	status: BackgroundTaskStatus,
	spaceId: string,
	documentId: string,
	selectionText: string,
	persistInDocument: boolean,
	resultText: string,
	error: string,
	createdAtMs: number,
	updatedAtMs: number,
};

export type BackgroundTaskKind = "explain-selection" | "expand-selection" | "research-selection";

export type BackgroundTaskStatus = "queued" | "running" | "succeeded" | "failed" | "unknown";

export type ChatMessage = {
	role: ChatRole,
	content: string,
};

export type ChatOptions = ChatOptions_Serialize | ChatOptions_Deserialize;

export type ChatOptions_Deserialize = {
	model: string | null,
	temperature: number | null,
} & {
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	maxTokens: number | null,
} | {
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	max_tokens: number | null,
} & {
	spaceId: string | null,
} | {
	workspace_id: string | null,
};

export type ChatOptions_Serialize = {
	model: string | null,
	temperature: number | null,
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	maxTokens: number | null,
	spaceId: string | null,
};

export type ChatResponse = {
	/**
	 *  Final assistant content. Non-streaming today; the field is named
	 *  `token` for parity with the old TS `StreamEvent.token` so the
	 *  renderer doesn't need a rename.
	 */
	token: string,
	done: boolean,
	/**  Empty when the call succeeded. */
	error: string,
};

export type ChatRole = "system" | "user" | "assistant";

export type ChatStreamArgs = ChatStreamArgs_Serialize | ChatStreamArgs_Deserialize;

export type ChatStreamArgs_Deserialize = {
	messages?: ChatMessage[],
} & ChatOptions_Deserialize;

export type ChatStreamArgs_Serialize = {
	messages: ChatMessage[],
} & ChatOptions_Serialize;

export type ControlAction = "start" | "stop" | "restart";

export type ControlArgs = {
	action: ControlAction,
};

export type ControlResult = {
	/**
	 *  `true` when the lifecycle action completed and the runtime is
	 *  (still) reachable. Mirrors the Electron-side `ok` boolean.
	 */
	ok: boolean,
	action: ControlAction,
	/**
	 *  Status snapshot taken right after the action ran, so renderer
	 *  consumers don't need a follow-up `status()` round-trip.
	 */
	status: DaemonStatus,
	/**  Optional human-readable note. `None` on success. */
	message: string | null,
};

export type CreateSpaceArgs = {
	spaceId?: string | null,
	displayName?: string | null,
};

/**
 *  Socket-introspection details. The Tauri shell embeds the daemon
 *  in-process, so the renderer-facing socket card has nothing to inspect
 *  and these fields stay `None`. The Electron shell populates them from
 *  the on-disk Unix socket. Kept here so the SDK type carries the
 *  richer shape both shells share.
 */
export type DaemonSocketInfo = {
	exists: boolean,
	uid: number | null,
	gid: number | null,
	mode: number | null,
	ownedByCurrentUser: boolean | null,
};

export type DaemonStatus = {
	/**
	 *  `true` when the renderer can talk to the runtime. Always `true`
	 *  on the Tauri side once `state.daemon.handle()` succeeds.
	 */
	reachable: boolean,
	/**
	 *  Identifier for the daemon transport. `<embedded:tauri>` on the
	 *  Tauri shell; the Unix socket path on the Electron shell.
	 */
	socketPath: string,
	peerId: string | null,
	listenAddrs: string[],
	/**  Populated when `status()` failed to talk to the runtime. */
	error: string | null,
	socket: DaemonSocketInfo | null,
};

export type DecideJoinArgs = {
	requestId: string,
	approve: boolean,
	role?: string,
	reason?: string,
};

export type DecideJoinResult = {
	decisionId: string,
	spaceId: string,
	subjectPeerId: string,
	decision: number,
	reason: string,
	approved: boolean,
};

export type DesktopError = { kind: "io"; message: string } | { kind: "invalid-input"; message: string } | { kind: "not-found"; message: string } | { kind: "daemon"; message: string } | { kind: "agent"; message: string } | { kind: "other"; message: string };

/**
 *  Renderer-facing payload. Tagged on `kind` to match the discriminated
 *  union the renderer's `@soma/desktop-db` parser accepts.
 */
export type DomainEvent = { kind: "document-blob-added"; spaceId: string; docId: string; cid: string; mime: string; size: number; name: string } | { kind: "join-submitted"; requestId: string; targetPeerId: string } | { kind: "join-decision"; fromPeerId: string; spaceId: string; decision: number; reason: string } | { kind: "join-failed"; targetPeerId: string; error: string } | { kind: "bot-status-changed"; spaceId: string; delegatePeerId: string; status: string };

export type EnqueueBackgroundTaskParams = {
	kind: BackgroundTaskKind,
	spaceId: string,
	documentId: string,
	selectionText: string,
	model: string | null,
	persistInDocument?: boolean,
};

export type EnsurePageArgs = {
	spaceId: string,
	pageId: string,
	title?: string,
	parentPageIds?: string[],
	createdAtMs?: number | null,
	updatedAtMs?: number | null,
};

export type IssueIssuerCapabilityArgs = {
	spaceId: string,
	targetPeerId: string,
	expiresAt: number,
	alias?: string | null,
	scopes?: string[],
};

export type JoinSpaceArgs = {
	spaceId: string,
	targetPeerId: string,
	targetMultiaddrs: string[],
	displayName?: string,
	deviceName?: string,
};

export type JoinSpaceResult = {
	requestId: string,
};

export type ListBackgroundTasksParams = {
	spaceId: string | null,
	limit: number | null,
};

export type ListSpacesArgs = {
	q: string | null,
	limit?: number,
	offset?: number,
};

export type ListSpacesResult = {
	spaces: StoredSpace[],
	limit: number,
	offset: number,
	nextOffset: number | null,
};

export type ModelKind = "chat" | "embed" | "unknown";

export type RerankCandidate = {
	id: string,
	content: string,
};

export type RerankParams = {
	query: string,
	candidates: RerankCandidate[],
	model: string | null,
	topN: number | null,
	spaceId: string | null,
};

export type RerankResult = {
	id: string,
	score: number | null,
	rank: number,
};

export type ResolveDriftParams = {
	leftUpdateBase64: string,
	rightUpdateBase64: string,
};

export type ResolveDriftResult = {
	mergedUpdateBase64: string,
};

export type RevokeMemberArgs = {
	spaceId: string,
	subjectPeerId: string,
	reason?: string,
};

export type SearchResult = {
	kind: string,
	id: string,
	title: string,
	spaceId: string,
};

export type SetPageParentsArgs = {
	spaceId: string,
	pageId: string,
	parentPageIds: string[],
};

export type SettingsGetArgs = {
	key: string,
};

export type SettingsSetArgs = {
	key: string,
	valueJson: string,
};

export type StageUploadArgs = {
	bytes: number[],
	mime: string,
	fileName?: string | null,
};

export type StagedUpload = {
	payloadPath: string,
	byteLength: number,
	mime: string,
	fileName: string | null,
	createdAtMs: number,
};

export type StoredDocument = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: boolean,
	updatedAtMs: number,
};

export type StoredJoinRequest = {
	requestId: string,
	spaceId: string,
	subjectPeerId: string,
	displayName: string,
	deviceName: string,
	requestedRole: number,
	createdAt: number,
};

export type StoredPage = {
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
};

export type StoredSpace = {
	spaceId: string,
	displayName: string,
	ownerPeerId: string,
	createdAt: number,
};

export type StoredSpaceBot = {
	spaceId: string,
	peerId: string,
	expiresAt: number,
	alias: string | null,
	status: string,
	scopes: string[],
};

export type StoredSpaceMember = {
	spaceId: string,
	peerId: string,
	role: string,
	expiresAt: number,
};

export type UpdatePageTitleArgs = {
	spaceId: string,
	pageId: string,
	title: string,
};

export type UpdateSpaceArgs = {
	spaceId: string,
	displayName: string,
};

export type UploadBlobArgs = {
	spaceId: string,
	docId?: string | null,
	mime: string,
	name: string,
	bytes: number[],
};

export type UploadBlobResult = {
	cid: string,
	size: number,
	mime: string,
	name: string,
};

export type UpsertDocumentArgs = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published?: boolean,
	updatedAtMs?: number | null,
};

export type WindowControlAction = "minimize" | "toggleMaximize" | "close";

export type WindowControlArgs = {
	action: WindowControlAction,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

