// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	dbStorageGet: (key: string) => typedError<string | null, DesktopError>(__TAURI_INVOKE("db_storage_get", { key })),
	dbStorageSet: (key: string, value: string) => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_set", { key, value })),
	dbStorageRemove: (key: string) => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_remove", { key })),
	dbStorageClear: () => typedError<null, DesktopError>(__TAURI_INVOKE("db_storage_clear")),
	dbStorageKeys: () => typedError<string[], DesktopError>(__TAURI_INVOKE("db_storage_keys")),
	settingsGet: (args: SettingsGetArgs) => typedError<string | null, DesktopError>(__TAURI_INVOKE("settings_get", { args })),
	settingsSet: (args: SettingsSetArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("settings_set", { args })),
	settingsGetAll: () => typedError<string, DesktopError>(__TAURI_INVOKE("settings_get_all")),
	windowControl: (args: WindowControlArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("window_control", { args })),
	windowMinimize: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_minimize")),
	windowToggleMaximize: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_toggle_maximize")),
	windowClose: () => typedError<null, DesktopError>(__TAURI_INVOKE("window_close")),
	daemonStatus: () => typedError<DaemonStatus, DesktopError>(__TAURI_INVOKE("daemon_status")),
	daemonReady: () => typedError<boolean, DesktopError>(__TAURI_INVOKE("daemon_ready")),
	daemonControl: (args: ControlArgs) => typedError<ControlResult, DesktopError>(__TAURI_INVOKE("daemon_control", { args })),
	spacesList: (args: {
	q: string | null,
	limit?: number,
	offset?: number,
} | null) => typedError<ListSpacesResult, DesktopError>(__TAURI_INVOKE("spaces_list", { args })),
	spacesCreate: (args: {
	spaceId?: string | null,
	displayName?: string | null,
} | null) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_create", { args })),
	spacesGet: (spaceId: string) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_get", { spaceId })),
	spacesUpdate: (args: UpdateSpaceArgs) => typedError<StoredSpace, DesktopError>(__TAURI_INVOKE("spaces_update", { args })),
	spacesDelete: (spaceId: string) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_delete", { spaceId })),
	spacesListMembers: (spaceId: string) => typedError<StoredSpaceMember[], DesktopError>(__TAURI_INVOKE("spaces_list_members", { spaceId })),
	spacesListMyMemberships: () => typedError<StoredSpaceMember[], DesktopError>(__TAURI_INVOKE("spaces_list_my_memberships")),
	spacesListBots: (spaceId: string) => typedError<StoredSpaceBot[], DesktopError>(__TAURI_INVOKE("spaces_list_bots", { spaceId })),
	spacesJoin: (args: JoinSpaceArgs) => typedError<JoinSpaceResult, DesktopError>(__TAURI_INVOKE("spaces_join", { args })),
	spacesDecideJoin: (args: DecideJoinArgs) => typedError<DecideJoinResult, DesktopError>(__TAURI_INVOKE("spaces_decide_join", { args })),
	spacesListJoinRequests: () => typedError<StoredJoinRequest[], DesktopError>(__TAURI_INVOKE("spaces_list_join_requests")),
	spacesRevokeMember: (args: RevokeMemberArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_revoke_member", { args })),
	spacesRevokeBot: (args: RevokeBotArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_revoke_bot", { args })),
	spacesIssueIssuerCapability: (args: IssueIssuerCapabilityArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("spaces_issue_issuer_capability", { args })),
	invitesCreate: (args: CreateInviteArgs) => typedError<StoredInvite, DesktopError>(__TAURI_INVOKE("invites_create", { args })),
	invitesList: (spaceId: string) => typedError<StoredInvite[], DesktopError>(__TAURI_INVOKE("invites_list", { spaceId })),
	invitesRevoke: (args: RevokeInviteArgs) => typedError<boolean, DesktopError>(__TAURI_INVOKE("invites_revoke", { args })),
	/**
	 *  Decode + offline-verify a `soma://invite/...` link. Touches no
	 *  network — safe to call before the user chooses to redeem it.
	 */
	invitesInspect: (link: string) => typedError<InviteInspection, DesktopError>(__TAURI_INVOKE("invites_inspect", { link })),
	invitesRedeem: (args: RedeemInviteArgs) => typedError<RedeemInviteResult, DesktopError>(__TAURI_INVOKE("invites_redeem", { args })),
	documentsUpsert: (args: UpsertDocumentArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("documents_upsert", { args })),
	documentsGet: (spaceId: string, documentId: string) => typedError<{
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: boolean,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_get", { spaceId, documentId })),
	documentsEnsurePage: (args: EnsurePageArgs) => typedError<StoredPage, DesktopError>(__TAURI_INVOKE("documents_ensure_page", { args })),
	documentsListPages: (spaceId: string) => typedError<StoredPage[], DesktopError>(__TAURI_INVOKE("documents_list_pages", { spaceId })),
	documentsUpdatePageTitle: (args: UpdatePageTitleArgs) => typedError<{
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_update_page_title", { args })),
	documentsSetPageParents: (args: SetPageParentsArgs) => typedError<{
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_set_page_parents", { args })),
	documentsGetDraft: (args: GetDraftArgs) => typedError<{
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: number,
	updatedAtMs: number,
} | null, DesktopError>(__TAURI_INVOKE("documents_get_draft", { args })),
	documentsUpsertDraft: (args: UpsertDraftArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("documents_upsert_draft", { args })),
	documentsPublish: (args: PublishDocumentArgs) => typedError<null, DesktopError>(__TAURI_INVOKE("documents_publish", { args })),
	blobsUpload: (args: UploadBlobArgs) => typedError<UploadBlobResult, DesktopError>(__TAURI_INVOKE("blobs_upload", { args })),
	blobsRead: (spaceId: string, cid: string) => typedError<number[] | null, DesktopError>(__TAURI_INVOKE("blobs_read", { spaceId, cid })),
	blobsStageUpload: (args: StageUploadArgs) => typedError<StagedUpload, DesktopError>(__TAURI_INVOKE("blobs_stage_upload", { args })),
	/**
	 *  Mime-aware stage: image payloads pass through verbatim, anything else
	 *  gets zipped before hitting the daemon. Returns the daemon's
	 *  `cid`/`size`/`mime`/`name` plus the synthesized `soma-blob://` URL.
	 */
	blobsStage: (args: StageBlobArgs) => typedError<StageBlobResult_Serialize, DesktopError>(__TAURI_INVOKE("blobs_stage", { args })),
	/**
	 *  Two-step upload's "stage to disk" leg. The wire shape matches
	 *  {@link blobs_stage_upload} — exposing it under the renderer-expected
	 *  command name keeps the SDK call site stable across shells.
	 */
	blobsStagePayload: (args: StageUploadArgs) => typedError<StagedUpload, DesktopError>(__TAURI_INVOKE("blobs_stage_payload", { args })),
	/**
	 *  Two-step upload's "consume staged payload" leg. Reads the staged file,
	 *  hands it to the mime-aware [`blobs_stage`] handler, then removes the
	 *  staging file on success.
	 */
	blobsStageFromPayload: (args: StageFromPayloadArgs) => typedError<StageBlobResult_Serialize, DesktopError>(__TAURI_INVOKE("blobs_stage_from_payload", { args })),
	agentChatStream: (args: ChatStreamArgs_Deserialize) => typedError<ChatResponse, DesktopError>(__TAURI_INVOKE("agent_chat_stream", { args })),
	agentListModels: (spaceId: string | null) => typedError<AgentModel_Serialize[], DesktopError>(__TAURI_INVOKE("agent_list_models", { spaceId })),
	agentRerank: (args: RerankParams) => typedError<RerankResult[], DesktopError>(__TAURI_INVOKE("agent_rerank", { args })),
	agentResolveDrift: (args: ResolveDriftParams) => typedError<ResolveDriftResult, DesktopError>(__TAURI_INVOKE("agent_resolve_drift", { args })),
	agentEnqueueBackgroundTask: (args: EnqueueBackgroundTaskParams) => typedError<BackgroundTask, DesktopError>(__TAURI_INVOKE("agent_enqueue_background_task", { args })),
	agentListBackgroundTasks: (args: {
	spaceId: string | null,
	limit: number | null,
} | null) => typedError<BackgroundTask[], DesktopError>(__TAURI_INVOKE("agent_list_background_tasks", { args })),
	agentConfigGetDefault: () => typedError<AgentProviderConfigView, DesktopError>(__TAURI_INVOKE("agent_config_get_default")),
	agentConfigGetSpace: (spaceId: string) => typedError<AgentProviderConfigView, DesktopError>(__TAURI_INVOKE("agent_config_get_space", { spaceId })),
	agentConfigSetDefault: (args: SetDefaultAgentProviderConfigArgs) => typedError<AgentProviderConfigView, DesktopError>(__TAURI_INVOKE("agent_config_set_default", { args })),
	agentConfigSetSpace: (args: SetSpaceAgentProviderConfigArgs) => typedError<AgentProviderConfigView, DesktopError>(__TAURI_INVOKE("agent_config_set_space", { args })),
	agentConfigClearDefault: () => typedError<boolean, DesktopError>(__TAURI_INVOKE("agent_config_clear_default")),
	agentConfigClearSpace: (spaceId: string) => typedError<boolean, DesktopError>(__TAURI_INVOKE("agent_config_clear_space", { spaceId })),
	agentConfigValidate: (args: ValidateAgentProviderConfigArgs) => typedError<ValidateAgentProviderConfigResult, DesktopError>(__TAURI_INVOKE("agent_config_validate", { args })),
	search: (query: string | null) => typedError<SearchResult[], DesktopError>(__TAURI_INVOKE("search", { query })),
	practiceListExercises: (spaceId: string | null) => typedError<Exercise[], DesktopError>(__TAURI_INVOKE("practice_list_exercises", { spaceId })),
	practiceSaveExercise: (args: ExerciseDraft) => typedError<Exercise, DesktopError>(__TAURI_INVOKE("practice_save_exercise", { args })),
	practiceRecordSession: (args: ExerciseAttempt) => typedError<RecordSessionResponse, DesktopError>(__TAURI_INVOKE("practice_record_session", { args })),
	practiceGenerateExercise: (args: GenerateExerciseInput) => typedError<ExerciseDraft, DesktopError>(__TAURI_INVOKE("practice_generate_exercise", { args })),
};

/* Types */
export type AgentModel = AgentModel_Serialize | AgentModel_Deserialize;

export type AgentModel_Deserialize = {
	name: string,
	kind: ModelKind,
	path: string,
	loaded: boolean,
	sizeBytes: number | null,
};

export type AgentModel_Serialize = {
	name: string,
	kind: ModelKind,
	path: string,
	loaded: boolean,
	sizeBytes?: number | null,
};

export type AgentProvider = 
/**  Any HTTP endpoint speaking the OpenAI REST shape (Ollama, vLLM, OpenAI proper, etc.). */
"open-ai-compatible";

/**
 *  Client-safe projection of one scope's AI provider config override
 *  row. A field is `null` when this scope doesn't override that column
 *  (it inherits — space from default, default from the compiled-in
 *  constants). `poll_interval_ms` is always `null` on a space-scope
 *  response (`get_space`) — only the default scope's poll interval is
 *  configurable; see `set_space`'s doc comment.
 */
export type AgentProviderConfigView = {
	provider: AgentProvider | null,
	baseUrl: string | null,
	hasApiKey: boolean,
	chatModel: string | null,
	embedModel: string | null,
	requestTimeoutMs: number | null,
	pollIntervalMs: number | null,
	/**
	 *  `null` when this scope has never been saved — every other field
	 *  is then also `null`.
	 */
	updatedAtMs: number | null,
};

export type AgentRuntimeEvent = AgentRuntimeEvent_Serialize | AgentRuntimeEvent_Deserialize;

export type AgentRuntimeEvent_Deserialize = ({ kind: "ready"; atMs: number; provider: AgentProvider; baseUrl: string }) & { error?: never; models?: never } | ({ kind: "status"; atMs: number; provider: AgentProvider; baseUrl: string; models: AgentModel_Deserialize[] }) & { error?: never } | ({ kind: "error"; atMs: number; provider: AgentProvider; baseUrl: string; error: string }) & { models?: never };

export type AgentRuntimeEvent_Serialize = ({ kind: "ready"; atMs: number; provider: AgentProvider; baseUrl: string }) & { error?: never; models?: never } | ({ kind: "status"; atMs: number; provider: AgentProvider; baseUrl: string; models: AgentModel_Serialize[] }) & { error?: never } | ({ kind: "error"; atMs: number; provider: AgentProvider; baseUrl: string; error: string }) & { models?: never };

/**
 *  Three-state write for the one field that never round-trips in
 *  cleartext (`AgentProviderConfigView` only ever exposes `hasApiKey`).
 *  Defaults to `Unchanged` when omitted, so a save that isn't touching
 *  the key field doesn't have to think about it.
 */
export type ApiKeyInput = { kind: "unchanged" } | { kind: "clear" } | { kind: "set"; value: string };

export type AppInfo = {
	name: string,
	version: string,
	tauri: string,
};

export type BackgroundTask = {
	taskId: string,
	kind: BackgroundTaskKind,
	status: BackgroundTaskStatus,
	spaceId: string,
	documentId: string,
	selectionText: string,
	persistInDocument: boolean,
	resultText: string,
	error: string,
	createdAtMs: number,
	updatedAtMs: number,
};

export type BackgroundTaskKind = "explain-selection" | "expand-selection" | "research-selection";

export type BackgroundTaskStatus = "queued" | "running" | "succeeded" | "failed" | "unknown";

export type ChatMessage = {
	role: ChatRole,
	content: string,
};

export type ChatOptions = ChatOptions_Serialize | ChatOptions_Deserialize;

export type ChatOptions_Deserialize = {
	model: string | null,
	temperature: number | null,
} & {
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	maxTokens: number | null,
} | {
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	max_tokens: number | null,
} & {
	spaceId: string | null,
} | {
	workspace_id: string | null,
};

export type ChatOptions_Serialize = {
	model: string | null,
	temperature: number | null,
	/**
	 *  Accept either `maxTokens` (current convention) or `max_tokens`
	 *  (the OpenAI-native field name the renderer still uses today).
	 */
	maxTokens: number | null,
	spaceId: string | null,
};

export type ChatResponse = {
	/**
	 *  Final assistant content. Non-streaming today; the field is named
	 *  `token` for parity with the old TS `StreamEvent.token` so the
	 *  renderer doesn't need a rename.
	 */
	token: string,
	done: boolean,
	/**  Empty when the call succeeded. */
	error: string,
};

export type ChatRole = "system" | "user" | "assistant";

export type ChatStreamArgs = ChatStreamArgs_Serialize | ChatStreamArgs_Deserialize;

export type ChatStreamArgs_Deserialize = {
	messages?: ChatMessage[],
} & ChatOptions_Deserialize;

export type ChatStreamArgs_Serialize = {
	messages: ChatMessage[],
} & ChatOptions_Serialize;

export type ControlAction = "start" | "stop" | "restart";

export type ControlArgs = {
	action: ControlAction,
};

export type ControlResult = {
	/**
	 *  `true` when the lifecycle action completed successfully. Any
	 *  underlying start/stop failure short-circuits via `?` before we
	 *  reach the result construction, so by the time this is built the
	 *  action has succeeded — even for `Stop`, where the post-action
	 *  runtime is intentionally unreachable. Mirrors the Electron-side
	 *  `ok` boolean.
	 */
	ok: boolean,
	action: ControlAction,
	/**
	 *  Status snapshot taken right after the action ran, so renderer
	 *  consumers don't need a follow-up `status()` round-trip.
	 */
	status: DaemonStatus,
	/**  Optional human-readable note. `None` on success. */
	message: string | null,
};

export type CreateInviteArgs = {
	spaceId: string,
	/**
	 *  Role string ("owner"/"editor"/"viewer"/"member"/"bot"); empty
	 *  defaults to "member".
	 */
	role?: string,
	/**  Seconds from now until expiry. `0` means "never expires". */
	ttlSecs: number,
	label?: string,
	/**  `false` (the default) makes the invite redeemable exactly once. */
	multiUse?: boolean,
};

export type CreateSpaceArgs = {
	spaceId?: string | null,
	displayName?: string | null,
};

/**
 *  Socket-introspection details. The Tauri shell embeds the daemon
 *  in-process, so the renderer-facing socket card has nothing to inspect
 *  and these fields stay `None`. The Electron shell populates them from
 *  the on-disk Unix socket. Kept here so the SDK type carries the
 *  richer shape both shells share.
 */
export type DaemonSocketInfo = {
	exists: boolean,
	uid: number | null,
	gid: number | null,
	mode: number | null,
	ownedByCurrentUser: boolean | null,
};

export type DaemonStatus = {
	/**
	 *  `true` when the renderer can talk to the runtime. Always `true`
	 *  on the Tauri side once `state.daemon.handle()` succeeds.
	 */
	reachable: boolean,
	/**
	 *  Identifier for the daemon transport. `<embedded:tauri>` on the
	 *  Tauri shell; the Unix socket path on the Electron shell.
	 */
	socketPath: string,
	peerId: string | null,
	listenAddrs: string[],
	/**  Populated when `status()` failed to talk to the runtime. */
	error: string | null,
	socket: DaemonSocketInfo | null,
};

export type DecideJoinArgs = {
	requestId: string,
	approve: boolean,
	role?: string,
	reason?: string,
};

export type DecideJoinResult = {
	decisionId: string,
	spaceId: string,
	subjectPeerId: string,
	decision: number,
	reason: string,
	approved: boolean,
};

/**
 *  A parsed `soma://` deep link, emitted on [`DEEP_LINK_EVENT`] in place
 *  of the raw URL string — see `startup::deep_link::dispatch` (the
 *  `desktop-app` binary) for the route table that produces this. Unlike
 *  [`DOMAIN_EVENT`] / [`AGENT_EVENT`], whose payload shapes are owned by
 *  `soma-daemon`/`soma-agentd` and kept out of this dependency-light
 *  crate, `DeepLinkRoute` genuinely belongs here: it's OS/URL-routing
 *  concern, not a daemon/agent-runtime concept, and keeping it a real
 *  type (rather than `serde_json::Value`) is what lets `desktop-app`
 *  register it with `tauri-specta` for a properly typed `@soma/sdk`
 *  binding.
 */
export type DeepLinkRoute = 
/**
 *  `soma://invite/<payload>` — a space invite link. `link` is the
 *  full original URL, ready to pass straight to
 *  `backend.invites.inspect({ link })`.
 */
{ kind: "invite"; link: string } | 
/**
 *  Any `soma://...` URL that didn't match a known route — carries the
 *  raw URL so nothing is silently dropped.
 */
{ kind: "unknown"; url: string };

export type DesktopError = { kind: "io"; message: string } | { kind: "invalid-input"; message: string } | { kind: "not-found"; message: string } | { kind: "daemon"; message: string } | { kind: "agent"; message: string } | 
/**
 *  Caller did not present a valid credential. Maps to HTTP 401 at the
 *  BFF boundary (`desktop-bff::error::ApiError::status`). The Tauri
 *  presenter never produces this variant — the in-process command
 *  surface has no network boundary to authenticate across.
 */
{ kind: "unauthenticated"; message: string } | { kind: "other"; message: string };

/**
 *  Renderer-facing payload. Tagged on `kind` so the renderer can
 *  discriminate each variant when consuming the `domain_event` channel.
 */
export type DomainEvent = { kind: "document-blob-added"; spaceId: string; docId: string; cid: string; mime: string; size: number; name: string } | { kind: "join-submitted"; requestId: string; targetPeerId: string } | { kind: "join-decision"; fromPeerId: string; spaceId: string; decision: number; reason: string } | { kind: "join-failed"; targetPeerId: string; error: string } | { kind: "bot-status-changed"; spaceId: string; delegatePeerId: string; status: string } | 
/**
 *  Renderer-broadcast: emitted by document/page command handlers
 *  when something changed at the page-list level for a space.
 */
{ kind: "pages-changed"; source: DomainEventSource; atMs: number; spaceId: string; reason: string | null } | 
/**
 *  Renderer-broadcast: emitted by document command handlers when a
 *  specific document's contents changed.
 */
{ kind: "document-changed"; source: DomainEventSource; atMs: number; spaceId: string; documentId: string; reason: string | null };

/**
 *  Source tag for renderer-broadcast events.
 * 
 *  `Daemon` is reserved for events that originate from the daemon
 *  firehose; today every variant in `DomainEvent` that uses this tag is
 *  emitted with `Renderer` from a command handler.
 */
export type DomainEventSource = "renderer" | "daemon";

/**
 *  Drafts row shape consumed by the renderer service today. `published`
 *  is `1 | 0` rather than a bool so the wire shape matches what the
 *  Electron handler emits.
 */
export type DraftRecord = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: number,
	updatedAtMs: number,
};

export type EnqueueBackgroundTaskParams = {
	kind: BackgroundTaskKind,
	spaceId: string,
	documentId: string,
	selectionText: string,
	model: string | null,
	persistInDocument?: boolean,
};

export type EnsurePageArgs = {
	spaceId: string,
	pageId: string,
	title?: string,
	parentPageIds?: string[],
	createdAtMs?: number | null,
	updatedAtMs?: number | null,
};

export type Exercise = {
	cid: string,
	message: string,
	meta: ExerciseMetadata,
};

export type ExerciseAttempt = {
	exerciseId: string,
	spaceId: string,
	wpm: number | null,
	accuracy: number | null,
	durationMs: number,
	completedAtMs: number,
};

export type ExerciseDifficulty = "beginner" | "intermediate" | "advanced";

export type ExerciseDraft = {
	message: string,
	meta: ExerciseDraftMetadata,
};

export type ExerciseDraftMetadata = {
	spaceId: string,
	topic?: string | null,
	difficulty?: ExerciseDifficulty | null,
	source?: ExerciseSource | null,
	tags?: string[] | null,
};

export type ExerciseMetadata = {
	id: string,
	spaceId: string,
	topic?: string | null,
	difficulty: ExerciseDifficulty,
	source: ExerciseSource,
	createdAtMs: number,
	length: number,
	tags?: string[] | null,
};

export type ExerciseSource = "manual" | "agent" | "imported";

export type GenerateExerciseInput = {
	spaceId: string,
	topic?: string | null,
	difficulty?: ExerciseDifficulty | null,
	length?: number | null,
};

export type GetDraftArgs = {
	spaceId: string,
	documentId: string,
};

/**
 *  Result of decoding + offline-verifying a `soma://invite/...` link —
 *  see `inspect`'s doc comment: this never touches the network.
 */
export type InviteInspection = {
	validity: InviteValidity,
	spaceId: string | null,
	spaceLabel: string | null,
	role: string | null,
	/**
	 *  The verified issuer when `validity == "valid"`; the UNVERIFIED
	 *  claimed signer otherwise (UI display only — never a trust
	 *  decision unless `validity == "valid"`).
	 */
	issuerPeerId: string | null,
	/**  Unix-seconds. `null` means "never expires". */
	expiresAt: number | null,
	bootstrapMultiaddrs: string[],
};

/**  Why an inspected invite link is or isn't usable. */
export type InviteValidity = "valid" | 
/**
 *  Decoded, but the signature doesn't verify (forged, corrupted, or
 *  hand-edited).
 */
"invalidSignature" | 
/**  Decoded and signature-valid, but past its expiry. */
"expired" | 
/**  Not a well-formed `soma://invite/...` link at all. */
"malformed";

export type IssueIssuerCapabilityArgs = {
	spaceId: string,
	targetPeerId: string,
	expiresAt: number,
	alias?: string | null,
	scopes?: string[],
	/**
	 *  Multiaddrs to dial `target_peer_id` on before sending the offer —
	 *  same shape/purpose as `JoinSpaceArgs.targetMultiaddrs`. Required
	 *  for a freshly-deployed bot with no prior connection; may be left
	 *  empty when the target is already reachable some other way.
	 */
	targetMultiaddrs?: string[],
};

export type JoinSpaceArgs = {
	spaceId: string,
	targetPeerId: string,
	targetMultiaddrs: string[],
	displayName?: string,
	deviceName?: string,
};

export type JoinSpaceResult = {
	requestId: string,
};

export type LeaderboardEntry = {
	spaceId: string,
	exerciseId: string,
	peerId?: string | null,
	displayName?: string | null,
	wpm: number | null,
	accuracy: number | null,
	completedAtMs: number,
};

export type ListBackgroundTasksParams = {
	spaceId: string | null,
	limit: number | null,
};

export type ListSpacesArgs = {
	q: string | null,
	limit?: number,
	offset?: number,
};

export type ListSpacesResult = {
	spaces: StoredSpace[],
	limit: number,
	offset: number,
	nextOffset: number | null,
};

export type ModelKind = "chat" | "embed" | "unknown";

/**
 *  Args for [`publish`]. There used to be two near-identical commands
 *  here (`queue_daemon_sync` and `sync_published`) that both just
 *  upserted the document and emitted a renderer event under a
 *  different name — see `publish`'s doc comment for why they were
 *  collapsed into this one.
 */
export type PublishDocumentArgs = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	updatedAtMs?: number | null,
};

export type RecordSessionResponse = {
	ok: boolean,
	leaderboard: LeaderboardEntry[],
};

export type RedeemInviteArgs = {
	link: string,
	displayName?: string,
	deviceName?: string,
};

export type RedeemInviteResult = {
	requestId: string,
};

export type RerankCandidate = {
	id: string,
	content: string,
};

export type RerankParams = {
	query: string,
	candidates: RerankCandidate[],
	model: string | null,
	topN: number | null,
	spaceId: string | null,
};

export type RerankResult = {
	id: string,
	score: number | null,
	rank: number,
};

export type ResolveDriftParams = {
	leftUpdateBase64: string,
	rightUpdateBase64: string,
};

export type ResolveDriftResult = {
	mergedUpdateBase64: string,
};

export type RevokeBotArgs = {
	spaceId: string,
	delegatePeerId: string,
	reason?: string,
};

export type RevokeInviteArgs = {
	spaceId: string,
	id: string,
};

export type RevokeMemberArgs = {
	spaceId: string,
	subjectPeerId: string,
	reason?: string,
};

/**
 *  One search hit. Maps cleanly onto `@soma/ui`'s `CommandPaletteItem`
 *  (`id`, `title`, `subtitle`, `section`): `spaceName` is the natural
 *  `subtitle`, `kind` plus `spaceId`/`id` are enough to build the right
 *  route and `onSelect`, and `snippet` (set for `document` hits only)
 *  gives the palette a reason to show *why* something matched.
 */
export type SearchResult = {
	kind: SearchResultKind,
	spaceId: string,
	spaceName: string,
	id: string,
	title: string,
	snippet: string | null,
	updatedAtMs: number,
};

export type SearchResultKind = "space" | "page" | "document";

/**
 *  Whole-state overwrite for the default scope. Every field (except
 *  `apiKey`, see [`ApiKeyInput`]) is a full replace: `null`/omitted
 *  clears that column back to "use the compiled-in default"; the UI is
 *  expected to always send the complete current form state, not a
 *  sparse patch (auto-save-on-blur per ADR-0005 §3).
 */
export type SetDefaultAgentProviderConfigArgs = {
	provider: AgentProvider | null,
	baseUrl: string | null,
	apiKey?: ApiKeyInput,
	chatModel: string | null,
	embedModel: string | null,
	requestTimeoutMs: number | null,
	pollIntervalMs: number | null,
};

export type SetPageParentsArgs = {
	spaceId: string,
	pageId: string,
	parentPageIds: string[],
};

/**
 *  Same contract as [`SetDefaultAgentProviderConfigArgs`], scoped to one
 *  space — with no `pollIntervalMs` field at all: the poll interval is
 *  process-wide, not overridable per space, so it isn't part of this
 *  scope's writable surface.
 */
export type SetSpaceAgentProviderConfigArgs = {
	spaceId: string,
	provider: AgentProvider | null,
	baseUrl: string | null,
	apiKey?: ApiKeyInput,
	chatModel: string | null,
	embedModel: string | null,
	requestTimeoutMs: number | null,
};

export type SettingsGetArgs = {
	key: string,
};

export type SettingsSetArgs = {
	key: string,
	valueJson: string,
};

/**
 *  Args for the mime-aware {@link stage} handler. Mirrors the renderer's
 *  `BlobStageParams` shape: image payloads pass through verbatim, anything
 *  else is zipped before hitting the daemon.
 */
export type StageBlobArgs = {
	spaceId: string,
	docId?: string | null,
	bytes: number[],
	mime: string,
	fileName?: string | null,
};

export type StageBlobResult = StageBlobResult_Serialize | StageBlobResult_Deserialize;

export type StageBlobResult_Deserialize = {
	cid: string,
	size: number,
	mime: string,
	name: string,
	url: string,
	variants?: StageBlobVariant_Deserialize[] | null,
};

export type StageBlobResult_Serialize = {
	cid: string,
	size: number,
	mime: string,
	name: string,
	url: string,
	variants?: StageBlobVariant_Serialize[] | null,
};

/**
 *  Thumbnail/variant descriptor. The Electron handler does not populate
 *  these yet — the field exists so the SDK type can carry future variants
 *  without a schema change.
 */
export type StageBlobVariant = StageBlobVariant_Serialize | StageBlobVariant_Deserialize;

/**
 *  Thumbnail/variant descriptor. The Electron handler does not populate
 *  these yet — the field exists so the SDK type can carry future variants
 *  without a schema change.
 */
export type StageBlobVariant_Deserialize = {
	cid: string,
	size: number,
	mime: string,
	name: string,
	url: string,
	width?: number | null,
	height?: number | null,
};

/**
 *  Thumbnail/variant descriptor. The Electron handler does not populate
 *  these yet — the field exists so the SDK type can carry future variants
 *  without a schema change.
 */
export type StageBlobVariant_Serialize = {
	cid: string,
	size: number,
	mime: string,
	name: string,
	url: string,
	width?: number | null,
	height?: number | null,
};

/**
 *  Args for the "consume a previously-staged payload and stage it as a
 *  blob" handler. Mirrors the renderer's `BlobStageFromPayloadParams`.
 */
export type StageFromPayloadArgs = {
	spaceId: string,
	docId?: string | null,
	payloadPath: string,
	mime: string,
	fileName?: string | null,
};

export type StageUploadArgs = {
	bytes: number[],
	mime: string,
	fileName?: string | null,
};

export type StagedUpload = {
	payloadPath: string,
	byteLength: number,
	mime: string,
	fileName: string | null,
	createdAtMs: number,
};

export type StoredDocument = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published: boolean,
	updatedAtMs: number,
};

export type StoredInvite = {
	spaceId: string,
	/**  Opaque id `RevokeInviteArgs.id` takes back. */
	id: string,
	/**  The full `soma://invite/...` link, ready to share. */
	link: string,
	issuerPeerId: string,
	role: string,
	/**  Unix-seconds; `0` means never expires. */
	expiresAt: number,
	label: string,
	multiUse: boolean,
	createdAt: number,
	/**  Unix-seconds; `0` means not revoked. */
	revokedAt: number,
	redeemedCount: number,
};

export type StoredJoinRequest = {
	requestId: string,
	spaceId: string,
	subjectPeerId: string,
	displayName: string,
	deviceName: string,
	requestedRole: number,
	createdAt: number,
};

export type StoredPage = {
	spaceId: string,
	pageId: string,
	title: string,
	parentPageIds: string[],
	createdAtMs: number,
	updatedAtMs: number,
};

export type StoredSpace = {
	spaceId: string,
	displayName: string,
	ownerPeerId: string,
	createdAt: number,
};

export type StoredSpaceBot = {
	spaceId: string,
	peerId: string,
	expiresAt: number,
	alias: string | null,
	status: string,
	scopes: string[],
};

export type StoredSpaceMember = {
	spaceId: string,
	peerId: string,
	role: string,
	expiresAt: number,
};

export type UpdatePageTitleArgs = {
	spaceId: string,
	pageId: string,
	title: string,
};

export type UpdateSpaceArgs = {
	spaceId: string,
	displayName: string,
};

export type UploadBlobArgs = {
	spaceId: string,
	docId?: string | null,
	mime: string,
	name: string,
	bytes: number[],
};

export type UploadBlobResult = {
	cid: string,
	size: number,
	mime: string,
	name: string,
};

export type UpsertDocumentArgs = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published?: boolean,
	updatedAtMs?: number | null,
};

export type UpsertDraftArgs = {
	spaceId: string,
	documentId: string,
	contentJson: string,
	published?: boolean,
	updatedAtMs?: number | null,
};

export type ValidateAgentProviderConfigArgs = {
	baseUrl: string,
	/**
	 *  Omitted/empty means "no Authorization header" — mirrors
	 *  `OpenAiProvider::auth_header`'s trim-and-check-empty rule.
	 */
	apiKey?: string | null,
	requestTimeoutMs?: number | null,
};

export type ValidateAgentProviderConfigResult = {
	ok: boolean,
	modelCount: number | null,
	/**
	 *  Present only when `ok` is false — a human-readable reason the UI
	 *  can show inline under the field (ADR-0005 §3: "errors surface
	 *  inline under the field").
	 */
	error: string | null,
};

export type WindowControlAction = "minimize" | "toggleMaximize" | "close";

export type WindowControlArgs = {
	action: WindowControlAction,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

