[package]
name = "soma-relayd"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
soma-relay = { workspace = true }
soma-metrics = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
mimalloc = { workspace = true }
axum = { workspace = true }
