[package]
name = "soma-botd"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
soma-core = { workspace = true, features = ["db"] }
soma-storage = { workspace = true }
soma-net = { workspace = true }
soma-common = { workspace = true }
soma-metrics = { workspace = true }
soma-peer = { workspace = true }
soma-proto-build = { workspace = true }

clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mimalloc = { workspace = true }

axum = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
futures = { workspace = true }
prometheus-client = { workspace = true }
prometheus-client-derive-encode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
prost-types = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true, features = ["any", "postgres", "sqlite", "migrate", "runtime-tokio-rustls"] }
