[package]
name = "tauri-command-utils"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = ["thiserror", "bad-request", "json-error"]
thiserror = ["dep:thiserror"]
bad-request = []
json-error = []
io = []
anyhow = ["dep:anyhow"]
daemon = ["dep:tonic"]
agent = []

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true }
tauri = { workspace = true }
thiserror = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
