/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returned by `SomaHandle.subscribeEvents`; calling `unsubscribe()` aborts
 * the translator task so the broadcast receiver is dropped and no more
 * events are delivered to the JS callback.
 */
export declare class EventSubscription {
  unsubscribe(): Promise<void>
}

export declare class SomaHandle {
  /** Gracefully shut down both embedded runtimes. Idempotent. */
  shutdown(): Promise<void>
  isRunning(): Promise<boolean>
  status(): Promise<DaemonStatusJs>
  /**
   * Subscribe to the daemon event firehose. `on_event` is called for every
   * translated event; call `unsubscribe()` on the returned `Subscription`
   * to stop. Backpressure: a 256-slot mpsc buffers between the broadcast
   * translator and the JS callback; lagged events are dropped silently.
   *
   * Disables `CalleeHandled` (the napi-rs default) by setting the const
   * generic to `false`, so the JS callback signature stays
   * `(event) => void` rather than `(err, event) => void`. The translator
   * task self-terminates if `call` returns `Status::Closing` (the napi env
   * is being torn down, typically during `shutdown`).
   */
  subscribeEvents(onEvent: (event: DaemonEventJs) => void): Promise<EventSubscription>
  listSpaces(input: ListSpacesInputJs): Promise<ListSpacesOutputJs>
  createSpace(input: CreateSpaceInputJs): Promise<CreateSpaceResultJs>
  getSpace(spaceId: string): Promise<SpaceRecordJs>
  updateSpace(input: UpdateSpaceInputJs): Promise<SpaceRecordJs>
  deleteSpace(spaceId: string): Promise<boolean>
  listSpaceMembers(spaceId: string): Promise<Array<SpaceMemberJs>>
  listMyMemberships(): Promise<Array<SpaceMemberJs>>
  /**
   * List bots within `space_id`. Wraps [`DaemonHandle::list_space_bots`].
   * Returns `SpaceBotJs` (peer + alias + expires_at + status + scopes).
   * `status` is derived (`expired` from `expires_at`); `scopes` are
   * stored + plumbed for forward-looking visibility only — runtime
   * authorisation enforcement is NOT yet implemented.
   */
  listSpaceBots(spaceId: string): Promise<Array<SpaceBotJs>>
  uploadBlob(input: UploadBlobInputJs): Promise<UploadBlobResultJs>
  readBlob(spaceId: string, cid: string): Promise<ReadBlobResultJs | null>
  ensurePage(input: EnsurePageInputJs): Promise<PageRecordJs>
  listPages(spaceId: string): Promise<Array<PageRecordJs>>
  updatePageTitle(spaceId: string, pageId: string, title: string): Promise<PageRecordJs | null>
  setPageParents(spaceId: string, pageId: string, parentPageIds: Array<string>): Promise<PageRecordJs | null>
  upsertDocument(input: UpsertDocumentInputJs): Promise<void>
  getDocument(spaceId: string, documentId: string): Promise<DocumentRecordJs | null>
  joinSpace(input: JoinSpaceInputJs): Promise<string>
  listJoinRequests(): Promise<Array<JoinRequestRecordJs>>
  decideJoin(input: DecideJoinInputJs): Promise<JoinDecisionRecordJs>
  revokeSpace(input: RevokeSpaceInputJs): Promise<boolean>
  discoverSpaces(): Promise<Array<DiscoveredSpaceJs>>
  issueIssuerCapability(input: IssueIssuerCapabilityInputJs): Promise<boolean>
  agentStatus(): Promise<AgentStatusJs>
  listModels(): Promise<Array<ModelInfoJs>>
  rerank(query: string, candidates: Array<RerankCandidateJs>, topN: number): Promise<RerankResultJs>
  resolveDrift(local: Buffer, remote: Buffer): Promise<Buffer>
}

export interface AgentStatusJs {
  version: string
  defaultChatModel: string
  defaultEmbedModel: string
  models: Array<ModelInfoJs>
}

export interface CreateSpaceInputJs {
  spaceId: string
  displayName: string
}

export interface CreateSpaceResultJs {
  spaceId: string
  ownerPeerId: string
}

/**
 * Flat-shape mirror of `daemon_types::DaemonEventRecord` for the napi
 * boundary. JS callers switch on `kind` ("document-blob-added",
 * "join-submitted", "join-decision", "join-failed") and read the fields
 * relevant to that kind. Irrelevant fields are populated with empty strings
 * (or `0` for `size`) since napi `#[napi(object)]` can't express
 * discriminated unions cleanly.
 */
export interface DaemonEventJs {
  kind: string
  spaceId: string
  docId: string
  cid: string
  mime: string
  size: number
  name: string
  requestId: string
  targetPeerId: string
  fromPeerId: string
  decision: number
  reason: string
  error: string
  delegatePeerId: string
  status: string
}

export interface DaemonStatusJs {
  peerId: string
  listenAddrs: Array<string>
}

export interface DecideJoinInputJs {
  requestId: string
  approve: boolean
  role: string
  reason: string
}

export interface DiscoveredSpaceJs {
  spaceId: string
  displayName: string
  tags: Array<string>
}

export interface DocumentRecordJs {
  spaceId: string
  documentId: string
  contentJson: string
  published: boolean
  updatedAtMs: number
}

export interface EnsurePageInputJs {
  spaceId: string
  pageId: string
  title: string
  parentPageIds: Array<string>
  createdAtMs: number
  updatedAtMs: number
}

export interface IssueIssuerCapabilityInputJs {
  spaceId: string
  targetPeerId: string
  expiresAt: number
  /**
   * Optional human alias for the Bots-tab list view. Empty / whitespace
   * strings are dropped at the daemon boundary.
   */
  alias?: string
  /**
   * Operator-typed scope identifiers from the Add form. Forwarded to
   * storage as-is; not enforced at runtime.
   */
  scopes: Array<string>
}

export interface JoinDecisionRecordJs {
  decisionId: string
  spaceId: string
  subjectPeerId: string
  decision: number
  reason: string
  approved: boolean
  createdAtMs: number
}

export interface JoinRequestRecordJs {
  requestId: string
  spaceId: string
  subjectPeerId: string
  displayName: string
  deviceName: string
  requestedRole: number
  createdAt: number
}

export interface JoinSpaceInputJs {
  spaceId: string
  displayName: string
  deviceName: string
  targetPeerId: string
  targetMultiaddrs: Array<string>
}

export interface ListSpacesInputJs {
  q?: string
  limit: number
  offset: number
}

export interface ListSpacesOutputJs {
  spaces: Array<SpaceRecordJs>
  limit: number
  offset: number
  nextOffset?: number
}

export interface ModelInfoJs {
  name: string
  path: string
  loaded: boolean
  sizeBytes?: number
}

export interface PageRecordJs {
  spaceId: string
  pageId: string
  title: string
  parentPageIds: Array<string>
  createdAtMs: number
  updatedAtMs: number
}

export interface ReadBlobResultJs {
  data: Buffer
  size: number
  mime: string
}

export interface RerankCandidateJs {
  id: string
  text: string
}

export interface RerankHitJs {
  id: string
  score: number
}

export interface RerankResultJs {
  hits: Array<RerankHitJs>
}

export interface RevokeSpaceInputJs {
  spaceId: string
  subjectPeerId: string
  reason: string
}

/**
 * Bot-shaped wire record for `list_space_bots`. `alias` flows from the
 * issuer-capability row; renderer hydrates `bot-<peerSuffix>` only if
 * the user never typed one in the Add form. `status` is the persistent
 * state with `expired` derived from `expires_at` at read time —
 * renderer renders it as-is. `scopes` are the operator-typed scope
 * identifiers, empty for pre-migration rows.
 *
 * NOTE: scopes are stored + plumbed only — NOT enforced at runtime.
 */
export interface SpaceBotJs {
  spaceId: string
  peerId: string
  expiresAt: number
  alias?: string
  status: string
  /**
   * Operator-typed scope identifiers. Empty for pre-migration rows
   * or when the user left the scopes field blank.
   */
  scopes: Array<string>
}

export interface SpaceMemberJs {
  spaceId: string
  peerId: string
  role: string
  expiresAt: number
}

export interface SpaceRecordJs {
  spaceId: string
  displayName: string
  ownerPeerId: string
  createdAt: number
}

/**
 * Start the Soma embedded runtimes (peer + agent) and return a handle that
 * keeps them alive. Both run in the napi-rs tokio runtime owned by this
 * addon; the caller does not provide one.
 */
export declare function start(config: StartConfig): Promise<SomaHandle>

export interface StartConfig {
  daemonDbPath: string
  blobDir: string
  identityPath?: string
  listenAddrs?: Array<string>
  bootstrapAddrs?: Array<string>
  rendezvousAddrs?: Array<string>
  relayAddrs?: Array<string>
  enableMdns?: boolean
}

export interface UpdateSpaceInputJs {
  spaceId: string
  displayName: string
}

export interface UploadBlobInputJs {
  spaceId: string
  data: Buffer
  mime: string
  name: string
  docId: string
}

export interface UploadBlobResultJs {
  cid: string
  size: number
  mime: string
  name: string
}

export interface UpsertDocumentInputJs {
  spaceId: string
  documentId: string
  contentJson: string
  published: boolean
  updatedAtMs: number
}
