[package]
name = "soma-app"
description = "A Tauri App"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "soma_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
soma-proto-build = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { version = "0.5", features = ["util"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
derive_builder = { workspace = true }
hyper = { version = "1", default-features = false, features = ["client", "http1"] }

mime = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
tauri-plugin-deep-link = { workspace = true }
tauri-plugin-log = { workspace = true }
tauri-command-utils = { workspace = true, features = ["thiserror", "bad-request", "json-error", "io", "anyhow", "daemon", "agent"] }

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\"))".dependencies]
tauri-plugin-single-instance = { workspace = true }
fix-path-env = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"
